name: moments
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_neumorphic: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/global-search.png
    - assets/logo.png
    - assets/play-cricle.png
    - assets/video-vertical.png