name: moments
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_neumorphic: ^3.0.3
  camera: any
  image_picker: any
  path_provider: any
  image_editor_pro: any
  video_player: any
  flutter_swiper: any
  intl: ^0.17.0
  glassmorphism: ^3.0.0
  intl_phone_field: ^3.1.0
  page_view_indicators: ^2.0.0
  hexagonal_grid_widget: ^1.0.1
  hexagon: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/global-search.png
    - assets/logo.png
    - assets/play-cricle.png
    - assets/video-vertical.png
